[buildPlans.FiraNext]
family = "Fira Next"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.FiraNext.variants]
  inherits = "ss05"

    [buildPlans.FiraNext.variants.design]
    four = "closed-serifless"
    six = "straight-bar"
    nine = "straight-bar"
    zero = "dotted"
    capital-g = "toothed-serifless-hookless"
    capital-j = "serifless"
    capital-m = "hanging-serifless"
    capital-q = "crossing"
    f = "flat-hook-serifless-crossbar-at-x-height"
    g = "single-storey-serifless"
    i = "serifed-flat-tailed"
    j = "serifless"
    l = "serifed-flat-tailed"
    r = "hookless-serifless"
    lower-iota = "serifed-flat-tailed"
    cyrl-em = "hanging-serifless"
    brace = "straight"
    ampersand = "closed"

  [buildPlans.FiraNext.ligations]
  inherits = "javascript"

[buildPlans.FiraNext.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.FiraNext.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.FiraNext.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.FiraNext.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.FiraNext.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.FiraNext.widths.Normal]
shape = 500
menu = 5
css = "normal"