/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTransfer: typeof import('element-plus/es')['ElTransfer']
    KeepAliveBoy: typeof import('./src/components/KeepAliveBoy.vue')['default']
    KeepAliveGirl: typeof import('./src/components/KeepAliveGirl.vue')['default']
    KeepAliveParent: typeof import('./src/components/KeepAliveParent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TransitionDemo: typeof import('./src/components/TransitionDemo.vue')['default']
  }
}
