/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Keep_alive_boy: typeof import('./src/components/keep_alive_boy.vue')['default']
    Keep_alive_girl: typeof import('./src/components/keep_alive_girl.vue')['default']
    Keep_alive_parent: typeof import('./src/components/keep_alive_parent.vue')['default']
    KeepAliveBoy: typeof import('./src/components/KeepAliveBoy.vue')['default']
    KeepAliveGirl: typeof import('./src/components/KeepAliveGirl.vue')['default']
    KeepAliveParent: typeof import('./src/components/KeepAliveParent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
