/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CSSModule: typeof import('./src/components/CSSModule.vue')['default']
    CustomDirective: typeof import('./src/components/CustomDirective.vue')['default']
    CustomDirective2: typeof import('./src/components/CustomDirective2.vue')['default']
    CustomDirectiveChild: typeof import('./src/components/CustomDirectiveChild.vue')['default']
    CustomHook: typeof import('./src/components/CustomHook.vue')['default']
    'D2vueBtn.ce': typeof import('./src/components/d2vue-btn.ce.vue')['default']
    DeepCSS: typeof import('./src/components/DeepCSS.vue')['default']
    DefineSlot: typeof import('./src/components/macro/DefineSlot.vue')['default']
    DefineSlotChild: typeof import('./src/components/macro/DefineSlotChild.vue')['default']
    DynamicCSS: typeof import('./src/components/DynamicCSS.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTransfer: typeof import('element-plus/es')['ElTransfer']
    KeepAliveBoy: typeof import('./src/components/KeepAliveBoy.vue')['default']
    KeepAliveGirl: typeof import('./src/components/KeepAliveGirl.vue')['default']
    KeepAliveParent: typeof import('./src/components/KeepAliveParent.vue')['default']
    ModelChild: typeof import('./src/components/ModelChild.vue')['default']
    ModelParent: typeof import('./src/components/ModelParent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlotSelector: typeof import('./src/components/SlotSelector.vue')['default']
    SlotSelectorChild: typeof import('./src/components/SlotSelectorChild.vue')['default']
    TransitionDemo: typeof import('./src/components/TransitionDemo.vue')['default']
    TransitionGroupDemo: typeof import('./src/components/TransitionGroupDemo.vue')['default']
    TransitionGroupDemo2: typeof import('./src/components/TransitionGroupDemo2.vue')['default']
    TransitionGroupDemo3: typeof import('./src/components/TransitionGroupDemo3.vue')['default']
    TransitionWithGSAP: typeof import('./src/components/TransitionWithGSAP.vue')['default']
    UnoCSS: typeof import('./src/components/UnoCSS.vue')['default']
    VueMacro: typeof import('./src/components/macro/VueMacro.vue')['default']
    VueMacroChild: typeof import('./src/components/macro/VueMacroChild.vue')['default']
    VuePluginDemo: typeof import('./src/components/VuePluginDemo.vue')['default']
  }
}
